apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openedx-db-secret
  namespace: default
spec:
  encryptedData:
    password: AgB6rE1V4UDPfqlRmbNksY2hFq2PUJKSJSVqMFBOKmU5sYhRlfaf1EY7anirhQFGgmPcgg6P1aSupYbHW7RHGwjz0Jtd3AqAwFkuhqs6XJlRYCjseP8A...
    username: AgBVGFWRDdwNjudM2hkTQY7f0wouzR/QdEV8RebNeygF+B8PImz8QkZ3Jahod2YFdw7ILs/vtlgfC23OJ0ocG0mZaTAUl5tDamiu4AM2PVALHrl7jv...
  template:
    metadata:
      creationTimestamp: null
      name: openedx-db-secret
      namespace: default
    type: Opaque
