apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudwatch-agent-config
  namespace: openedx
data:
  cloudwatch-agent-config.json: |
    {
      "logs": {
        "logs_collected": {
          "files": {
            "collect_list": [
              {
                "file_path": "/var/log/nginx/access.log",
                "log_group_name": "/aws/containerinsights/openedx/nginx-access"
              }
            ]
          }
        }
      }
    }
