apiVersion: v1
kind: Service
metadata:
  name: cms-loadbalancer
  namespace: openedx
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-1:123456789012:certificate/abc123-def456"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
  labels:
    app: openedx
    component: cms
    type: loadbalancer
spec:
  selector:
    app: openedx
    component: cms
  ports:
  - name: https
    port: 443
    targetPort: 8001
    protocol: TCP
  - name: http
    port: 80
    targetPort: 8001
    protocol: TCP
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 0.0.0.0/0
  externalTrafficPolicy: Local
